#!/bin/bash
#PBS -q arm
#PBS -l select=1:ncpus=64
#PBS -l walltime=01:00:00
#PBS -N Kelvin_Helmoltz_Growth_Rate_1n4p16t

module switch PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel
module load cray-fftw
module load cray-jemalloc

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

export MPICH_MAX_THREAD_SAFETY=multiple
aprun -n 4 -S 2 -d 16 ../../swift_mpi --hydro --threads=16 kelvinHelmholtzGrowthRate.yml

