#!/bin/bash
#PBS -q arm
#PBS -l select=1:ncpus=64:ompthreads=2
#PBS -l walltime=01:00:00
#PBS -N Kelvin_Helmoltz_Growth_Rate_1n2p16t

module switch PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel
module load cray-fftw
module load cray-jemalloc

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

export MPICH_MAX_THREAD_SAFETY=multiple
aprun -N 2 -n 2 -S 1 -d 16 -j 1 ../../swift_mpi --hydro --threads=16 kelvinHelmholtzGrowthRate.yml

